# Generated by Django 6.0 on 2025-12-15 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
        ('posts', '0003_post_categoria_alter_categoria_creada_and_more'),
    ]

    operations = [
    ]
